server:
  address: localhost
  port: 8080

base:
  detection:
    minDistance: !!float 0.0
    maxDistance: !!float 500.0
    averageDistance: !!float 300.0
  mesh:
    maxSize: 99

osm:
  uri:
    basic: https://nominatim.openstreetmap.org/?q=
    params:
      type: > 
        hotel, 
        supermarket
      location: tallinn
      format: json

errors:
  default_error_distance: -1.0f